FROM openjdk:11-jre-slim

ARG CLOVA_API_KEY
ARG GOOGLE_MAPS_API_KEY
ARG CLOVA_APIGW_KEY
ARG CLOVA_REQUEST_ID

ARG CHATBOT_API_KEY
ARG CHATBOT_APIGW_KEY
ARG CHATBOT_REQUEST_ID

ENV CLOVA_API_KEY=${CLOVA_API_KEY}
ENV GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
ENV CLOVA_APIGW_KEY=${CLOVA_APIGW_KEY}
ENV CLOVA_REQUEST_ID=${CLOVA_REQUEST_ID}

ENV CHATBOT_API_KEY=${CHATBOT_API_KEY}
ENV CHATBOT_APIGW_KEY=${CHATBOT_APIGW_KEY}
ENV CHATBOT_REQUEST_ID=${CHATBOT_REQUEST_ID}

ARG JAR_FILE=build/libs/solt-0.0.1-SNAPSHOT.jar

COPY ${JAR_FILE} app.jar

ENTRYPOINT [ "java", "-jar", "app.jar" ]
